# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CRGsLPQhRSID0tHuX4_DRmIJ8FAVjrd
"""

from flask import Flask, request, render_template, jsonify
import mlflow.pyfunc
import pandas as pd
import os

app = Flask(__name__)

# ✅ Load the MLflow Model
model = mlflow.pyfunc.load_model("models:/Best_Marketing_Model/latest")

# ✅ Path to `data_copy.csv` in the Git-tracked `data/` folder
DATA_FILE_PATH = "data/data_copy.csv"

@app.route("/", methods=["GET"])
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    # ✅ Check if file exists in Git-tracked repo
    if not os.path.exists(DATA_FILE_PATH):
        return jsonify({"error": "data_copy.csv not found in repo"}), 400

    # ✅ Load data_copy.csv from Git
    df = pd.read_csv(DATA_FILE_PATH)

    # ✅ Run Model Prediction
    predictions = model.predict(df)
    df["predictions"] = predictions

    return df.to_json(orient="records"), 200

if __name__ == "__main__":
    app.run(port=5000)