name: 🚀 Manual Data Transformation

on:
  workflow_dispatch:  # ✅ Allows manual trigger from GitHub UI

jobs:
  transform-data:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set Up Python 3.10 (Airflow Compatibility)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install Dependencies
        run: pip install --no-cache-dir -r src/requirements.txt

      - name: 🚀 Run Data Transformation Script
        run: python src/data_pipeline.py

      - name: 🏗️ Debug: Check If File Exists
        run: |
          if [ -f data/data_training.parquet ]; then
            echo "✅ Transformed data found!"
          else
            echo "❌ ERROR: Transformed data is missing!"
            exit 1
          fi

      - name: 🏗️ Commit Transformed Data Back to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/data_training.parquet
          git commit -m "✅ Updated transformed data_training.parquet" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gbhasin0828/MMX_ML_Ops.git
